---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  params:
    - name: message
      type: string
      default: "Hello from Tekton"
  steps:
    - name: say
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo "$(params.message)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: Cleans the shared workspace (optional helper)
  workspaces:
    - name: source
  steps:
    - name: clean
      image: registry.access.redhat.com/ubi8/ubi
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        rm -rf ./* .[^.]* || true
        ls -la

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: This task will run nosetests on the provided input.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
    - name: database_uri
      description: Database connection string
      type: string
      default: "sqlite:///test.db"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.database_uri)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        python -m pip install --upgrade pip wheel
        pip install -qr requirements.txt
        echo "Running nosetests $(params.args)"
        nosetests $(params.args)